"""empty message

Revision ID: 9ad31547c942
Revises: 1e52e4caefdc
Create Date: 2021-07-07 23:34:51.940820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad31547c942'
down_revision = '1e52e4caefdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('img', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
